const fs = require('fs');

const content = fs.readFileSync('data.js', 'utf8');
let dataStr = content.replace('const strikeData = ', '').replace(/;\n?$/, '').trim();
let data = new Function('return ' + dataStr)();

let elektrostal = data.find(x => x.id === 240);
let kotovsk = data.find(x => x.id === 241);

if (elektrostal) {
  elektrostal.date = '19.07.2026';
  elektrostal.ru.details = 'Логистический центр Wildberries в Электростали, один из крупнейших хабов компании в Подмосковье, подвергся разрушительному удару беспилотников. По заявлениям украинской стороны, склад использовался российским ВПК для перераспределения подсанкционных деталей, необходимых для сборки дронов и навигационных систем. Атака спровоцировала колоссальный пожар, который уничтожил около 350 тысяч квадратных метров складских площадей, что составляет порядка 7% всей логистической инфраструктуры маркетплейса. Пожар сопровождался сильнейшим задымлением, а экстренные службы боролись с огнём несколько дней. В результате удара один человек скончался в больнице, ещё десятки сотрудников получили ранения различной степени тяжести. Финансовый ущерб от потери самого здания, оборудования и сгоревших товаров оценивается аналитиками в астрономическую сумму от 30 до 100 миллиардов рублей. Этот инцидент стал мощнейшим ударом не только по военной логистике, но и по всей цепочке поставок компании.';
  elektrostal.uk.details = "Логістичний центр Wildberries в Електросталі, один із найбільших хабів компанії в Підмосков'ї, зазнав руйнівного удару безпілотників. За заявами української сторони, склад використовувався російським ВПК для перерозподілу підсанкційних деталей, необхідних для збирання дронів та навігаційних систем. Атака спровокувала колосальну пожежу, яка знищила близько 350 тисяч квадратних метрів складських площ, що становить близько 7% усієї логістичної інфраструктури маркетплейсу. Пожежа супроводжувалася надзвичайно сильним задимленням, а екстрені служби боролися з вогнем кілька днів. Унаслідок удару одна людина померла в лікарні, ще десятки співробітників отримали поранення різного ступеня тяжкості. Фінансовий збиток від втрати самої будівлі, обладнання та згорілих товарів оцінюється аналітиками в астрономічну суму від 30 до 100 мільярдів рублів. Цей інцидент став потужним ударом не лише по військовій логістиці, а й по всьому ланцюгу постачання компанії.";
  elektrostal.en.details = "The Wildberries logistics centre in Elektrostal, one of the company's largest hubs in the Moscow region, suffered a devastating drone strike. According to Ukrainian officials, the warehouse was being utilized by the Russian military-industrial complex to redistribute sanctioned components essential for assembling drones and navigation systems. The attack triggered a massive fire that completely destroyed approximately 350,000 square meters of warehouse space, wiping out nearly 7% of the marketplace's total logistics capacity. The blaze was accompanied by severe smoke, and emergency services battled the flames for several days. As a result of the strike, one person died in the hospital and dozens of other employees sustained varying degrees of injuries. Financial losses from the destruction of the building, equipment, and incinerated goods are estimated by analysts at a staggering 30 to 100 billion rubles. This incident delivered a crippling blow not only to military logistics but to the company's entire supply chain.";
}

if (kotovsk) {
  kotovsk.date = '19.07.2026';
  kotovsk.ru.details = 'Логистический хаб Wildberries в городе Котовск Тамбовской области был атакован ударными дронами ввиду его стратегического расположения вблизи «Тамбовского порохового завода». Этот завод является одним из ключевых предприятий России по производству пороха и зарядов для артиллерии, и, по имеющимся данным, складская инфраструктура маркетплейса была интегрирована в логистику ВПК. В результате точного попадания БПЛА на объекте вспыхнул мощный пожар, полностью уничтоживший хранившиеся там запасы и часть строений. К сожалению для сотрудников ночной смены, последствия оказались трагическими: подтверждена гибель семи человек, ещё несколько десятков получили ранения. Спасательные работы и тушение пожара продолжались длительное время из-за масштабов возгорания и угрозы повторных детонаций на соседних промышленных площадках. Этот удар наглядно продемонстрировал уязвимость складов двойного назначения, которые используются для нужд российской армии.';
  kotovsk.uk.details = "Логістичний хаб Wildberries у місті Котовськ Тамбовської області був атакований ударними дронами з огляду на його стратегічне розташування поблизу «Тамбовського порохового заводу». Цей завод є одним із ключових підприємств Росії з виробництва пороху та зарядів для артилерії, і, за наявними даними, складська інфраструктура маркетплейсу була інтегрована в логістику ВПК. Унаслідок точного влучання БПЛА на об'єкті спалахнула потужна пожежа, яка повністю знищила запаси, що там зберігалися, та частину будівель. На жаль для працівників нічної зміни, наслідки виявилися трагічними: підтверджено загибель семи осіб, ще кілька десятків отримали поранення. Рятувальні роботи та гасіння пожежі тривали довгий час через масштаби займання та загрозу повторних детонацій на сусідніх промислових майданчиках. Цей удар наочно продемонстрував уразливість складів подвійного призначення, які використовуються для потреб російської армії.";
  kotovsk.en.details = "The Wildberries logistics hub in Kotovsk, Tambov Oblast, was targeted by strike drones due to its strategic location near the Tambov Powder Plant. This plant is one of Russia's key enterprises for producing gunpowder and artillery charges, and reports indicate that the marketplace's warehouse infrastructure had been integrated into military logistics. A direct UAV hit sparked a massive fire at the facility, completely obliterating the stored inventory and sections of the buildings. For the night shift employees, the consequences were tragic: the deaths of seven people were confirmed, with several dozen more injured. Rescue and firefighting operations lasted for a considerable time due to the massive scale of the blaze and the risk of secondary detonations at adjacent industrial sites. This strike starkly demonstrated the vulnerability of dual-use warehouses that are secretly repurposed to supply the Russian military.";
}

const newContent = 'const strikeData = ' + JSON.stringify(data, null, 2) + ';\n';
fs.writeFileSync('data.js', newContent);
console.log('Updated Wildberries data in data.js');
